debug = true

[pista]
x11 = true
interval = 1.0
log_level = 3
pad_left = " "
pad_right = " "
separator = "    "
expiry_character = "_"
slots = [
    {len = 25, ttl = 2, cmd = "while :; do date --rfc-3339=seconds; sleep 1; done"},
]
